services:
  app:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    entrypoint: >
      sh -c "apt-get update && apt-get install -y git && pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && tail -f /dev/null"
      