from recursiva.builtins import *

dictionary = {
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '': {'func': noOperation, 'args': 1},
    '%': {'func': moder, 'args': 2},
    '&': {'func': ander, 'args': 2},
    '*': {'func': multiply, 'args': 2},
    '+': {'func': adder, 'args': 2},
    '-': {'func': subtract, 'args': 2},
    '/': {'func': divide, 'args': 2},
    ';': {'func': plusOne, 'args': 1},
    '(': {'func': upperAlphabet, 'args': 0},
    ')': {'func': lowerAlphabet, 'args': 0},
    '?': {'func': getValue, 'args': 1, 'useInterpreterRef': 1},
    '<': {'func': lesserThan, 'args': 2},
    '>': {'func': greaterThan, 'args': 2},
    '=': {'func': compare, 'args': 2},
    'A': {'func': listify, 'args': 1},
    'B': {'func': ranger, 'args': 1},
    'C': {'func': character, 'args': 1},
    'D': {'func': doubler, 'args': 1},
    "E": {'func': joinWithNewLine, 'args': 1},
    "F": {'func': floater, 'args': 1},
    'G': {'func': appendNewLine, 'args': 1},
    'H': {'func': halver, 'args': 1},
    "I": {'func': integerer, 'args': 1},
    'J': {'func': joiner, 'args': 2},
    'K': {'func': pythonExec, 'args': 1},
    'L': {'func': length, 'args': 1},
    'M': {'func': recursivaEval, 'args': 1, 'useInterpreterRef': 1},
    'N': {'func': isIn, 'args': 2},
    'O': {'func': order, 'args': 1},
    'P': {'func': printer, 'args': 1},
    'Q': {'func': splitter, 'args': 2},
    "R": {'func': squareRoot, 'args': 1},
    'S': {'func': square, 'args': 1},
    'T': {'func': sliceFromLeft, 'args': 1},
    'U': {'func': pythonEval, 'args': 1},
    'V': {'func': stringer, 'args': 1},
    'W': {'func': stringify, 'args': 1},
    'Y': {'func': getPiece, 'args': 2},
    'Z': {'func': slice, 'args': 3},
    '_': {'func': reverse, 'args': 1},
    "^": {'func': exponent, 'args': 2},
    '`': {'func': assign, 'args': 2, 'useInterpreterRef': 1},
    'g': {'func': noOperation, 'args': 1},
    'h': {'func': noOperation, 'args': 1},
    'i': {'func': noOperation, 'args': 1},
    'j': {'func': joinWithNothing, 'args': 1},
    'k': {'func': sorter, 'args': 2, 'useInterpreterRef': 1},
    'l': {'func': noOperation, 'args': 1},
    'm': {'func': mapper, 'args': 2, 'useInterpreterRef': 1},
    'n': {'func': noOperation, 'args': 1},
    'o': {'func': noOperation, 'args': 1},
    'p': {'func': palindromizer, 'args': 1},
    'q': {'func': noOperation, 'args': 2},
    'r': {'func': stringReplace, 'args': 3},
    's': {'func': summer, 'args': 1},
    't': {'func': noOperation, 'args': 1},
    'u': {'func': noOperation, 'args': 1},
    'v': {'func': noOperation, 'args': 1},
    'w': {'func': whiler, 'args': 2, 'useInterpreterRef': 1},
    'x': {'func': finder, 'args': 2},
    'y': {'func': noOperation, 'args': 1},
    'z': {'func': noOperation, 'args': 1},
    '{': {'func': forEach, 'args': 2, 'useInterpreterRef': 1},
    '|': {'func': orer, 'args': 2},
    '~': {'func': minusOne, 'args': 1},
}
